services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: codestream
      MYSQL_USER: jungmini
      MYSQL_PASSWORD: qwer1234
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - codestream

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    command: redis-server --requirepass jungmini
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - codestream

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - codestream

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    networks:
      - codestream

networks:
  codestream:
    driver: bridge