services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: chat
      MYSQL_USER: jungmini
      MYSQL_PASSWORD: qwer1234
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data
