spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${database-local-url}/chat
      username: ${database-local-username}
      password: ${database-local-password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ChatConnectionPool
      minimum-idle: 10 # 최소 커넥션
      maximum-pool-size: 20 # 최대 커넥션
      idle-timeout: 60000
      connection-timeout: 30000

  sql:
    init:
      mode: always

logging:
  level:
    chat.jungmini.me.database.mapper: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod