spring.application.name: codestream-api
spring.profiles.active: local

spring:
  config:
    import:
      - s3.yml
      - logging.yml
      - database.yml
      - redis.yml
      - mail.yml

  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local

oauth2:
  google:
    base-url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${oauth-google-client-id}
    client-secret: ${oauth-google-client-secret}
    redirect-uri: ${oauth-google-local-redirect-uri}

  kakao:
    auth-server-base-url: https://kauth.kakao.com
    resource-server-base-url: https://kapi.kakao.com
    client-id: ${oauth-kakao-client-id}
    redirect-uri: ${oauth-kakao-local-redirect-uri}


---
spring.config.activate.on-profile: prod

oauth2:
  google:
    base-url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${oauth-google-client-id}
    client-secret: ${oauth-google-client-secret}
    redirect-uri: ${oauth-google-prod-redirect-uri}

  kakao:
    auth-server-base-url: https://kauth.kakao.com
    resource-server-base-url: https://kapi.kakao.com
    client-id: ${oauth-kakao-client-id}
    redirect-uri: ${oauth-kakao-prod-redirect-uri}